# Generated by Django 3.0.8 on 2020-08-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20200821_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
