# Generated by Django 3.0.8 on 2020-09-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20200923_1333'),
        ('Favorite', '0002_auto_20200923_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites', to='Post.Post'),
        ),
    ]
